"""empty message

Revision ID: 36754465086e
Revises: 47dfb2478c2c
Create Date: 2019-06-20 08:22:14.470227

"""

# revision identifiers, used by Alembic.
revision = '36754465086e'
down_revision = '47dfb2478c2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
