"""empty message

Revision ID: 47dfb2478c2c
Revises: e2fe8b16bca3
Create Date: 2019-06-19 13:34:46.178487

"""

# revision identifiers, used by Alembic.
revision = '47dfb2478c2c'
down_revision = 'e2fe8b16bca3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('image', sa.String(length=300), nullable=True))
    op.add_column('movie', sa.Column('note', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'note')
    op.drop_column('movie', 'image')
    # ### end Alembic commands ###
