"""empty message

Revision ID: 4fab6bb259a9
Revises: 47dfb2478c2c
Create Date: 2019-06-20 20:59:02.706120

"""

# revision identifiers, used by Alembic.
revision = '4fab6bb259a9'
down_revision = '47dfb2478c2c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('user_first_name', sa.String(length=300), nullable=False),
    sa.Column('user_last_name', sa.String(length=300), nullable=False),
    sa.Column('movie', sa.String(length=300), nullable=False),
    sa.Column('note', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_first_name', 'user_last_name', 'movie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
