"""empty message

Revision ID: 6181f65210a1
Revises: 4fab6bb259a9
Create Date: 2019-06-20 21:02:11.386121

"""

# revision identifiers, used by Alembic.
revision = '6181f65210a1'
down_revision = '4fab6bb259a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
