"""empty message

Revision ID: 6cd787db072b
Revises: 9651589b36b5
Create Date: 2019-06-20 08:24:34.643777

"""

# revision identifiers, used by Alembic.
revision = '6cd787db072b'
down_revision = '9651589b36b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
