"""empty message

Revision ID: 9651589b36b5
Revises: 36754465086e
Create Date: 2019-06-20 08:22:52.910047

"""

# revision identifiers, used by Alembic.
revision = '9651589b36b5'
down_revision = '36754465086e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
