"""empty message

Revision ID: e2fe8b16bca3
Revises: 51e2c29ad95
Create Date: 2019-06-18 12:56:16.302542

"""

# revision identifiers, used by Alembic.
revision = 'e2fe8b16bca3'
down_revision = '51e2c29ad95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('length', sa.String(length=300), nullable=True),
    sa.Column('genre', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
